# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.96.0"

default_platform :android

platform :android do
  before_all do
    ENV["CRASHLYTICS_API_TOKEN"] = "d340877592487019d618eada69d27ba7f41dad0f"
    ENV["CRASHLYTICS_BUILD_SECRET"] = "668e828def754610dab7a26b1d9434de77f2ba234f14b9b04586e434a95ff1b7"
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(
      task: "test",
      flavor: "Staging",
      build_type: "Debug",
    )
    gradle(
      task: "test",
      flavor: "Playstore",
      build_type: "Debug",
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :staging do
    gradle(
      task: 'assemble',
      flavor: 'Staging',
      build_type: 'Release'
    )
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: 'assemble',
      flavor: 'Playstore',
      build_type: 'Release'
    )
    supply
  end

  desc "Assemble playstore version"
  lane :playstore do 
    gradle(task: "assemblePlaystore")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
